CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  first_time_login BOOLEAN DEFAULT TRUE,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  cpf VARCHAR(14) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  birthdate DATE NOT NULL,
  last_time_login TIMESTAMP,
  last_time_logout TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  role VARCHAR(20) NOT NULL
);