eureka:
  instace:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Admin-facade
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8095

zipkin:
  base-url: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0