eureka:
  instace:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: user
          uri: http://localhost:8085
          predicates:
            - Path=/user/**
          filters:
            - ApiGatewayAuthFilter
        - id: admin
          uri: http://localhost:8095
          predicates:
            - Path=/admin/**
          filters:
            - ApiGatewayAuthFilter

server:
  port: 8222
zipkin:
  base-url: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0
